services:
  app:
    build: .
    image: system-integrator-app:latest
    container_name: system-integrator-app
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
